openapi: 3.0.3

info:
    title: Music service API
    description: Api for music app
    version: 1.0.0

servers:
    - url: http://localhost:2215/api/v1

tags:
    - name: Server
    - name: Handlers

paths:
    # Server
    /ping:
        get:
            tags:
                - "Server"
            summary: Returns ping from server
            responses:
                "200":
                    description: returns ping from server
    /swagger:
        get:
            tags:
                - "Server"
            summary: "Returns ui of the swagger file"
            responses:
                "200":
                    description: Returns swagger file"
                "500":
                    description: An error occurred on the server
                    $ref: "#/components/responses/serverError"

    # Other
    /music-list:
        get:
            tags:
                - "Handlers"
            summary: "Returns list of the audios"
            responses:
                "200":
                    description: "Returns array of the audios"
                    $ref: "#/components/responses/tracksList"
                "500":
                    description: An error occurred on the server
                    $ref: "#/components/responses/serverError"

components:
    responses:
        tracksList:
            description: "Tracks list"
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            type: object
                            properties:
                                trackInfo:
                                    type: object
                                    properties:
                                        author:
                                            type: string
                                        name:
                                            type: string
                                        id:
                                            type: number
                                        path:
                                            type: string

        # Errors
        # The track was not found
        trackNotFound:
            description: The track was not found
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            message:
                                type: string
                                example: Трек не был найден
                            code:
                                type: number
                                example: 404
        # An error occurred on the server
        serverError:
            description: An error occurred on the server
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            message:
                                type: string
                                example: Произошла ошибка с сервером. Повторите позже
                            code:
                                type: number
                                example: 500
